# Generated by Django 6.0.7 on 2026-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("zelle", "Zelle"),
                    ("chime", "Chime"),
                    ("apple_pay", "Apple Pay"),
                    ("cash_app", "Cash App"),
                    ("e_transfer", "E-Transfer"),
                    ("venmo", "Venmo"),
                    ("crypto", "Crypto"),
                ],
                default="zelle",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
