# Generated by Django 6.0.7 on 2026-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_address_line1_order_address_line2_order_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("zelle", "Zelle"),
                    ("chime", "Chime"),
                    ("apple_pay", "Apple Pay"),
                    ("cash_app", "Cash App"),
                    ("e_transfer", "E-Transfer"),
                    ("venmo", "Venmo"),
                    ("pay_id", "PayID"),
                    ("crypto", "Crypto"),
                ],
                max_length=20,
            ),
        ),
    ]
